In [2]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv("anime.csv")
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  GintamaÂ°TV (51 eps)Apr 2015 - Mar 2016605,113...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [49]:
#make a new colum for episode count (feature extraction)
def extract_episode(txt):
    check = False
    data = ""
    for i in txt:
        if i == "(":
            check  = True
            continue
        if i == ")":
            break
        if check:
            data = data + i
    return data

In [50]:
df["Episodes"] = df["Title"].apply(extract_episode)

In [55]:
df["Episodes"] = df["Episodes"].str.replace(" eps","")

In [58]:
df["Episodes"] = df["Episodes"].astype(int)

In [62]:
type(df.loc[0]["Episodes"])

numpy.int64

In [64]:
df.head()

   Rank                                              Title  Score  Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3     4  GintamaÂ°TV (51 eps)Apr 2015 - Mar 2016605,113...   9.06        51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10

In [69]:
#now we have to extract timestamp
def extraction_time(txt):
    check = False
    data = ""
    for i in range(len(txt)):
        if txt[i] == ")":
            for j in range(i+1,i+20):
                data +=  txt[j]
            return data

In [71]:
df["Total Time"] = df["Title"].apply(extraction_time)

In [72]:
df.head()

,Rank,Title,Score,Episodes,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"GintamaÂ°TV (51 eps)Apr 2015 - Mar 2016605,113...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [73]:
#for months
from dateutil.relativedelta import relativedelta
from datetime import datetime

def calculate_total_month(period):
    try:
        start_str, end_str = period.split(' - ')
        start_date = datetime.strptime(start_str, '%b %Y')
        end_date = datetime.strptime(end_str, '%b %Y')
        r = relativedelta(end_date, start_date)
        return r.years + 12 + r.months + 1
    except:
        return None

df['Months'] = df['Total Time'].apply(calculate_total_month)

In [75]:
df.head()

,Rank,Title,Score,Episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,17
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,18
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,15
3,4,"GintamaÂ°TV (51 eps)Apr 2015 - Mar 2016605,113...",9.06,51,Apr 2015 - Mar 2016,24
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,16

In [77]:
#which anime has the highest score
df[df['Score'] == df['Score'].max()]

,Rank,Title,Score,Episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010,17

In [80]:
#top 5 highest scoring anime 
df['Title'].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    GintamaÂ°TV (51 eps)Apr 2015 - Mar 2016605,113...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: object

In [81]:
#which anime has the highest episode count
df[df["Episodes"] == df["Episodes"].max()]

,Rank,Title,Score,Episodes,Total Time,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,27

In [86]:
#animes with top 5 episode count
df.sort_values(by = "Episodes",ascending=False).head(5)

,Rank,Title,Score,Episodes,Total Time,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,27
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,26
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,24
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,19
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,19

In [87]:
#which is the longest running anime
df[df["Months"] == df["Months"].max()]

,Rank,Title,Score,Episodes,Total Time,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,27

In [1]:
import os
print(os.getcwd())

C:\Users\hp\anime_project